// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/6/2026, 3:40:46 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/ResoluteProjects/abrm/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/plugins/**/*.{js,ts,mjs}","D:/ResoluteProjects/abrm/app/composables/**/*.{js,ts,mjs}","D:/ResoluteProjects/abrm/app/utils/**/*.{js,ts,mjs}","D:/ResoluteProjects/abrm/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/ResoluteProjects/abrm/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;